version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
      target: backend
    volumes:
      - shared-data:/app/images
    ports:
      - "80:80"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    volumes:
      - shared-data:/front/images
    ports:
      - "3000:3000"

volumes:
  shared-data:
